In [32]:
"""
NUMPY TUTORIAL - LEARN BY DOING
Complete exercises in order. Try to solve before looking at solutions.
Estimated time: 7-10 hours total (1-2h per day for a week)

Run this in Jupyter Notebook or VS Code with Python interactive window.
"""

import numpy as np
import time
import math

# =============================================================================
# DAY 1-2: BASICS - ARRAYS, INDEXING, BASIC OPERATIONS
# =============================================================================

print("="*60)
print("SECTION 1: CREATING ARRAYS")
print("="*60)

# NumPy array = fast, efficient container for numerical data
# Like Python list but: faster, less memory, more operations

# Different ways to create arrays:
a = np.array([1, 2, 3, 4, 5])  # from list
b = np.zeros(5)  # array of zeros
c = np.ones((3, 3))  # 3x3 array of ones
d = np.arange(0, 10, 2)  # like range(): start, stop, step
e = np.linspace(0, 1, 5)  # 5 numbers evenly spaced between 0 and 1
f = np.random.rand(3, 3)  # 3x3 array of random numbers [0, 1)

print(f"Array a: {a}")
print(f"Array b: {b}")
print(f"Array e (linspace): {e}")

# EXERCISE 1.1: Create array of numbers from 10 to 50 with step 5
# Expected: [10 15 20 25 30 35 40 45 50]
# Your code here:
ex1_1 = None
X = np.random.rand(2,4,5)
print(X)

a = np.linspace(10,50,5).reshape(5,1)
b = np.linspace(10,50,5)
print(b@a)

# Solution (don't look until you try!):
# ex1_1 = np.arange(10, 51, 5)

SECTION 1: CREATING ARRAYS
Array a: [1 2 3 4 5]
Array b: [0. 0. 0. 0. 0.]
Array e (linspace): [0.   0.25 0.5  0.75 1.  ]
[[[0.81353446 0.6305969  0.65491817 0.76248604 0.12212475]
  [0.84910514 0.78618077 0.16633881 0.94317562 0.3662135 ]
  [0.29426368 0.41505846 0.85084224 0.82395531 0.27837906]
  [0.71664552 0.08791488 0.05264392 0.95659948 0.10223825]]

 [[0.43288711 0.92613395 0.58669259 0.59345445 0.3671017 ]
  [0.17697885 0.87061775 0.09903211 0.2212518  0.45203471]
  [0.86986512 0.52677278 0.45677902 0.34686219 0.24659636]
  [0.26435392 0.45294065 0.25591615 0.76877508 0.97870179]]]
[5500.]


In [118]:
rg =np.random.default_rng(1)
a = np.arange(1,19).reshape(2,3,3)
a*=3
# print(a)
b=np.sqrt(rg.random((2,3,3)))
# b[:6:10] = 100
print(b, "\n"+"-" * 19)
# print(b[...,1], "\n"+"-" * 19)

for firstAxis in b.flat:
    print(firstAxis)
print("\n"+"-" * 19)
print(b.sum(axis=1))
# print(b+a)
print(b.dtype.name)
# c = np.fromfunction()

print(b.ravel())
# print(b.reshape(4,-1))

print(np.concatenate((a,b), axis=0))

b.flat[::2] = 0
print(b)



[[[0.7154171  0.97491728 0.37968357]
  [0.97398637 0.55841871 0.65063542]
  [0.90978162 0.63968675 0.74134586]]

 [[0.16600938 0.86805133 0.73358252]
  [0.57422271 0.88793508 0.5506313 ]
  [0.67342252 0.36611705 0.63491179]]] 
-------------------
0.715417098412008
0.9749172766578379
0.3796835691989235
0.973986369071582
0.5584187067161034
0.6506354193959745
0.9097816187527872
0.6396867486271396
0.7413458623834489
0.16600937697331547
0.8680513283641738
0.7335825197067323
0.5742227063597295
0.8879350783860295
0.5506313006828117
0.6734225192853678
0.36611705402393474
0.6349117942258824

-------------------
[[2.59918509 2.17302273 1.77166485]
 [1.4136546  2.12210346 1.91912561]]
float64
[0.7154171  0.97491728 0.37968357 0.97398637 0.55841871 0.65063542
 0.90978162 0.63968675 0.74134586 0.16600938 0.86805133 0.73358252
 0.57422271 0.88793508 0.5506313  0.67342252 0.36611705 0.63491179]
[[[ 3.          6.          9.        ]
  [12.         15.         18.        ]
  [21.         24.         

In [131]:
import numpy as np
from scipy import io, integrate, linalg, signal
from scipy.sparse.linalg import cg, eigs

print(np.shape(a))
print(a)
print('-----')
print(a[:,:,::2])
# print(np.eye(5, dtype=int))


(2, 3, 3)
[[[ 3  6  9]
  [12 15 18]
  [21 24 27]]

 [[30 33 36]
  [39 42 45]
  [48 51 54]]]
-----
[[[ 3  9]
  [12 18]
  [21 27]]

 [[30 36]
  [39 45]
  [48 54]]]
