In [30]:
"""
NUMPY TUTORIAL - LEARN BY DOING
Complete exercises in order. Try to solve before looking at solutions.
Estimated time: 7-10 hours total (1-2h per day for a week)

Run this in Jupyter Notebook or VS Code with Python interactive window.
"""

import numpy as np
import time
import math

# =============================================================================
# DAY 1-2: BASICS - ARRAYS, INDEXING, BASIC OPERATIONS
# =============================================================================

print("="*60)
print("SECTION 1: CREATING ARRAYS")
print("="*60)

# NumPy array = fast, efficient container for numerical data
# Like Python list but: faster, less memory, more operations

# Different ways to create arrays:
a = np.array([1, 2, 3, 4, 5])  # from list
b = np.zeros(5)  # array of zeros
c = np.ones((3, 3))  # 3x3 array of ones
d = np.arange(0, 10, 2)  # like range(): start, stop, step
e = np.linspace(0, 1, 5)  # 5 numbers evenly spaced between 0 and 1
f = np.random.rand(3, 3)  # 3x3 array of random numbers [0, 1)

print(f"Array a: {a}")
print(f"Array b: {b}")
print(f"Array e (linspace): {e}")

# EXERCISE 1.1: Create array of numbers from 10 to 50 with step 5
# Expected: [10 15 20 25 30 35 40 45 50]
# Your code here:
ex1_1 = None
X = np.random.rand(2,4,5)
print(X)

a = np.linspace(10,50,5).reshape(5,1)
print(np.sin(a)*2)

# Solution (don't look until you try!):
# ex1_1 = np.arange(10, 51, 5)

SECTION 1: CREATING ARRAYS
Array a: [1 2 3 4 5]
Array b: [0. 0. 0. 0. 0.]
Array e (linspace): [0.   0.25 0.5  0.75 1.  ]
[[[0.76376437 0.93317493 0.31793726 0.04541725 0.44753892]
  [0.80332645 0.74364363 0.65688566 0.80740379 0.81018912]
  [0.65800362 0.22710019 0.48188932 0.57326919 0.41890456]
  [0.24391678 0.71283243 0.7216442  0.23025792 0.89677375]]

 [[0.8104624  0.50007419 0.33936188 0.84224407 0.20655676]
  [0.88072424 0.16664382 0.43254371 0.76379246 0.67865646]
  [0.18204124 0.52224408 0.58208141 0.36899245 0.54693977]
  [0.54447941 0.49705215 0.86537068 0.37461724 0.8717873 ]]]
[[-1.08804222]
 [ 1.8258905 ]
 [-1.97606325]
 [ 1.49022632]
 [-0.52474971]]
